import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header/Header";

import { Audiowide } from "next/font/google";
import Footer from "./Footer/Footer";

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-audiowide",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${audiowide.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
