import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header/Header";
import Head from "next/head";

import { Audiowide } from "next/font/google";
import Footer from "../components/Footer/Footer";

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-audiowide",
});

export const metadata: Metadata = {
  title: "Spirit",
  description: "Generated by create Spirit",
  metadataBase: new URL("https://myspiritwallet.com/"),
  keywords: ["Spirit", "Wallet", "Crypto", "Blockchain", "Telegram"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/assets/logo_spirit_white.svg"
          type="image/svg+xml"
        />
      </head>
      <body className={`${audiowide.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
